# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='service_owner',
            field=models.CharField(default='vistek', max_length=20),
        ),
    ]
