# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceManage', '0002_servicelist_service_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='service_status',
            field=models.CharField(default='false', max_length=5),
        ),
    ]
