# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GZYService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=20)),
                ('ClientCount', models.IntegerField()),
                ('CheckDeviceCount', models.IntegerField()),
                ('DeviceCount', models.IntegerField()),
                ('Clients_info', models.CharField(max_length=1000)),
                ('Pipelines', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LSDService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('error_msg', models.CharField(max_length=50)),
                ('cpuUseRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpuCount', models.IntegerField()),
                ('physicCpuCount', models.IntegerField()),
                ('memSize', models.IntegerField()),
                ('useMem', models.IntegerField()),
                ('aviableMemSize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('memUseRate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rigisterSucessCount', models.IntegerField()),
                ('registerFaildCount', models.IntegerField()),
                ('registerSucessDeviceList', models.CharField(max_length=1000)),
                ('registerFailDeviceList', models.CharField(max_length=1000)),
            ],
        ),
    ]
