# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gzyservice',
            name='service_id',
        ),
    ]
