# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0004_auto_20160628_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='GZYDeviceService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='abc', max_length=20)),
                ('ClientCount', models.IntegerField()),
                ('CheckDeviceCount', models.IntegerField()),
                ('DeviceCount', models.IntegerField()),
                ('Clients_info', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='GZYMediaService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='abc', max_length=20)),
                ('ClientCount', models.IntegerField()),
                ('MaxDeviceCount', models.IntegerField()),
                ('UpRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DownRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Clients_info', models.CharField(max_length=10000)),
                ('Pipelines', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='GZYService',
        ),
    ]
